<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="GoogleApi" Version="5.8.11" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
  </ItemGroup>

</Project>
